CREATE TABLE IF NOT EXISTS "users" (
	"username"	TEXT,
	"active"	INTEGER,
	PRIMARY KEY("username")
);

CREATE TABLE IF NOT EXISTS "startdata" (
	"id"	TEXT,
	"username"	TEXT,
	"startDay"	INTEGER,
	"startMonth"	INTEGER,
	"startYear"	INTEGER,
	"overallLvl"	INTEGER,
	"overallExp"	INTEGER,
	"attackLvl"	INTEGER,
	"attackExp"	INTEGER,
	"defenceLvl"	INTEGER,
	"defenceExp"	INTEGER,
	"strengthLvl"	INTEGER,
	"strengthExp"	INTEGER,
	"hitpointsLvl"	INTEGER,
	"hitpointsExp"	INTEGER,
	"rangedLvl"	INTEGER,
	"rangedExp"	INTEGER,
	"prayerLvl"	INTEGER,
	"prayerExp"	INTEGER,
	"magicLvl"	INTEGER,
	"magicExp"	INTEGER,
	"cookingLvl"	INTEGER,
	"cookingExp"	INTEGER,
	"woodcuttingLvl"	INTEGER,
	"woodcuttingExp"	INTEGER,
	"fletchingLvl"	INTEGER,
	"fletchingExp"	INTEGER,
	"fishingLvl"	INTEGER,
	"fishingExp"	INTEGER,
	"firemakingLvl"	INTEGER,
	"firemakingExp"	INTEGER,
	"craftingLvl"	INTEGER,
	"craftingExp"	INTEGER,
	"smithingLvl"	INTEGER,
	"smithingExp"	INTEGER,
	"miningLvl"	INTEGER,
	"miningExp"	INTEGER,
	"herbloreLvl"	INTEGER,
	"herbloreExp"	INTEGER,
	"agilityLvl"	INTEGER,
	"agilityExp"	INTEGER,
	"thievingLvl"	INTEGER,
	"thievingExp"	INTEGER,
	"slayerLvl"	INTEGER,
	"slayerExp"	INTEGER,
	"farmingLvl"	INTEGER,
	"farmingExp"	INTEGER,
	"runecraftingLvl"	INTEGER,
	"runecraftingExp"	INTEGER,
	"hunterLvl"	INTEGER,
	"hunterExp"	INTEGER,
	"constructionLvl"	INTEGER,
	"constructionExp"	INTEGER,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "enddata" (
	"id"	TEXT,
	"username"	TEXT,
	"endDay"	INTEGER,
	"endMonth"	INTEGER,
	"endYear"	INTEGER,
	"overallLvl"	INTEGER,
	"overallExp"	INTEGER,
	"attackLvl"	INTEGER,
	"attackExp"	INTEGER,
	"defenceLvl"	INTEGER,
	"defenceExp"	INTEGER,
	"strengthLvl"	INTEGER,
	"strengthExp"	INTEGER,
	"hitpointsLvl"	INTEGER,
	"hitpointsExp"	INTEGER,
	"rangedLvl"	INTEGER,
	"rangedExp"	INTEGER,
	"prayerLvl"	INTEGER,
	"prayerExp"	INTEGER,
	"magicLvl"	INTEGER,
	"magicExp"	INTEGER,
	"cookingLvl"	INTEGER,
	"cookingExp"	INTEGER,
	"woodcuttingLvl"	INTEGER,
	"woodcuttingExp"	INTEGER,
	"fletchingLvl"	INTEGER,
	"fletchingExp"	INTEGER,
	"fishingLvl"	INTEGER,
	"fishingExp"	INTEGER,
	"firemakingLvl"	INTEGER,
	"firemakingExp"	INTEGER,
	"craftingLvl"	INTEGER,
	"craftingExp"	INTEGER,
	"smithingLvl"	INTEGER,
	"smithingExp"	INTEGER,
	"miningLvl"	INTEGER,
	"miningExp"	INTEGER,
	"herbloreLvl"	INTEGER,
	"herbloreExp"	INTEGER,
	"agilityLvl"	INTEGER,
	"agilityExp"	INTEGER,
	"thievingLvl"	INTEGER,
	"thievingExp"	INTEGER,
	"slayerLvl"	INTEGER,
	"slayerExp"	INTEGER,
	"farmingLvl"	INTEGER,
	"farmingExp"	INTEGER,
	"runecraftingLvl"	INTEGER,
	"runecraftingExp"	INTEGER,
	"hunterLvl"	INTEGER,
	"hunterExp"	INTEGER,
	"constructionLvl"	INTEGER,
	"constructionExp"	INTEGER,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "admins" (
	"username"	TEXT NOT NULL,
	"password"	TEXT NOT NULL,
	PRIMARY KEY("username")
);
